### ISSUE TITLE
ok

### ISSUE THREAD

**Issue by Kathamii** [AlSalad/BYOD#9]

**Comment by AlSalad** [comment]
Sehr geehrte Kathamii,

unterlassen Sie weitere Aktivitäten auf unserem Repository.
Sollte es zu weiteren Vorfällen kommen, muss ich gerichtliche Maßnahmen
ergreifen.

Mit freundlichen Jagdrufen
Der Beschte

2018-02-23 13:19 GMT+01:00 Kathamii <notifications@github.com>:

**Comment by AlSalad** [comment]
Sehr geehrter Katharina-Maria Heer,

da Sie meiner Warnung nicht folge geleistet haben, haben wir jetzt offiziel
ein Problem.

Überweisen Sie 1€ an luka.kroeger@web.de per PayPal oder wir leaken
folgendes Bild:

[image: Inline-Bild 1]

Sie Haben 1 Stunde Bedenkzeit.

Mit grüßlichen Freunden
Luka

Am 23. Februar 2018 um 13:27 schrieb Luka Anonym <koopacopter@gmail.com>:
